[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
memoize = "0.4.2"
radix_fmt = "1.0.0"
regex = "1.11.1"

[lib]
name = "aoclibrary"
path = "src/lib.rs"

[[bin]]
name = "aocbin"
path = "src/main.rs"
